-- Lua Snippets
local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node
local c = ls.choice_node
local sn = ls.snippet_node

ls.add_snippets("lua", {
    s("fun", {
        t("function "),
        i(1, "name"),
        t("("),
        i(2),
        t({")", "  "}),
        i(3),
        t({"", "end"}),
    }),
    s("lfun", {
        t("local function "),
        i(1, "name"),
        t("("),
        i(2),
        t({")", "  "}),
        i(3),
        t({"", "end"}),
    }),
    s("req", {
        t("local "),
        i(1, "module"),
        t(" = require(\""),
        i(2, "module_name"),
        t("\")"),
    }),
    s("mod", {
        t("local M = {}"),
        t(""),
        t({"M."}),
        i(1, "function"),
        t(" = function("),
        i(2),
        t({")", "  "}),
        i(3),
        t({"", "end", "", "return M"}),
    }),
    s("tbl", {
        t("{"),
        t({"", "  "}),
        i(1),
        t({"", "}"}),
    }),
    s("pairs", {
        t("for "),
        i(1, "k"),
        t(", "),
        i(2, "v"),
        t(" in pairs("),
        i(3),
        t(") do"),
        t({"", "  "}),
        i(4),
        t({"", "end"}),
    }),
    s("ipairs", {
        t("for "),
        i(1, "i"),
        t(", "),
        i(2, "v"),
        t(" in ipairs("),
        i(3),
        t(") do"),
        t({"", "  "}),
        i(4),
        t({"", "end"}),
    }),
    s("if", {
        t("if "),
        i(1, "condition"),
        t(" then"),
        t({"", "  "}),
        i(2),
        t({"", "end"}),
    }),
    s("ife", {
        t("if "),
        i(1, "condition"),
        t(" then"),
        t({"", "  "}),
        i(2),
        t({"", "else", "  "}),
        i(3),
        t({"", "end"}),
    }),
    s("while", {
        t("while "),
        i(1, "condition"),
        t(" do"),
        t({"", "  "}),
        i(2),
        t({"", "end"}),
    }),
    s("repeat", {
        t("repeat"),
        t({"", "  "}),
        i(1),
        t({"", "until "}),
        i(2),
    }),
    s("class", {
        t("local "),
        i(1, "ClassName"),
        t(" = {}"),
        t({"", "  "}),
        t({""}),
        i(1, "ClassName"),
        t(".__index = "),
        i(1, "ClassName"),
        t({"", "", "function "}),
        i(1, "ClassName"),
        t("."),
        i(2, "new"),
        t("(self)"),
        t({"", "    local obj = {}", "    setmetatable(obj, self)", "    return obj", "  end", "", "  return "}),
        i(1, "ClassName"),
    }),
    s("print", {
        t("print("),
        i(1),
        t(")"),
    }),
    s("vimcmd", {
        t("vim.cmd(\""),
        i(1),
        t("\")"),
    }),
    s("keymap", {
        t("vim.keymap.set("),
        c(1, {
            t("\"n\""),
            t("\"i\""),
            t("\"v\""),
            t("\"t\""),
        }),
        t(", \""),
        i(2),
        t("\", function()"),
        t({"", "  "}),
        i(3),
        t({"", "end)"}),
    }),
    s("au", {
        t("vim.api.nvim_create_autocmd("),
        i(1, "event"),
        t(", {"),
        t({"", "  callback = function()", "    "}),
        i(2),
        t({"", "  end", "})"}),
    }),
    s("aug", {
        t("local "),
        i(1, "group"),
        t(" = vim.api.nvim_create_augroup(\""),
        i(2),
        t("\", { clear = true })"),
        t({"", ""}),
        t("vim.api.nvim_create_autocmd("),
        i(3, "event"),
        t(", {"),
        t({"", "  group = "}),
        i(1),
        t({",", "  callback = function()", "    "}),
        i(4),
        t({"", "  end", "})"}),
    }),
    s("lazy", {
        t("return {"),
        t({"", "  \""}),
        i(1, "plugin_name"),
        t("\","),
        t({"  "}),
        c(2, {
            t("lazy = true,"),
            t("event = \"VeryLazy\","),
            t("cmd = {\""),
            i(3),
            t("\"},"),
            sn(nil, {t("dependencies = {"), i(1), t("}")}),
        }),
        t({"", "}"}),
    }),
    s("plug", {
        t("return {"),
        t({"", "  "}),
        c(1, {
            t("\""),
            t("\""),
        }),
        i(2),
        t({"", "  config = function()", "    "}),
        i(3),
        t({"", "  end", "}"}),
    }),
})