os:
  editPreset: 'nvim'

gui:
  language: 'en'

git:
  autoForwardBranches: 'allBranches'
  branchPrefix: 'feature/'
  localBranchSortOrder: date #recency
  remoteBranchSortOrder: date #alphabetical
  commitPrefix:
    - pattern: "^\\w+\\/(\\w+-\\w+).*"
      replace: '$1 '
    - pattern: "^([^_]+)_.*" # Take all text prior to the first underscore
      replace: '$1 '
  paging:
    colorArg: always
    pager: delta --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
